import Head from "next/head";

import { AuthLayout } from "@/auth/containers";
import { PrivateRoute } from "@/auth/containers/PrivateRoute";
import { AppLayout } from "@/shared/components/AppLayout";

export default function Home() {
	return (
		<AuthLayout>
			<PrivateRoute>
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<AppLayout>
					<main>
						<div>Home</div>
					</main>
				</AppLayout>
			</PrivateRoute>
		</AuthLayout>
	);
}
